// This file is @generated by prost-build.
/// Connections rpc message container
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Connections {
    #[prost(oneof = "connections::Message", tags = "1, 2, 3, 4, 5, 6")]
    pub message: ::core::option::Option<connections::Message>,
}
/// Nested message and enum types in `Connections`.
pub mod connections {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        /// Request a list of all mesh nodes.
        /// libqaul returns an mesh_nodes_list message.
        #[prost(message, tag = "1")]
        MeshNodesRequest(super::MeshNodesRequest),
        /// returns a list of all mesh nodes and
        /// an information about why this message has been sent.
        #[prost(message, tag = "2")]
        MeshNodesList(super::MeshNodesList),
        /// Add a new mesh node address.
        /// libqaul returns an mesh_nodes_list message.
        #[prost(message, tag = "3")]
        MeshNodesAdd(super::MeshNodesEntry),
        /// Remove an mesh node address.
        /// libqaul returns an mesh_nodes_list message.
        #[prost(message, tag = "4")]
        MeshNodesRemove(super::MeshNodesEntry),
        /// Update an mesh node state.
        /// libqaul returns an mesh_nodes_list message.
        #[prost(message, tag = "5")]
        MeshNodesState(super::MeshNodesEntry),
        /// Rename mesh node.
        /// libqaul returns an mesh_nodes_list message.
        #[prost(message, tag = "6")]
        MeshNodesRename(super::MeshNodesEntry),
    }
}
/// UI request for mesh nodes list
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MeshNodesRequest {}
/// Mesh Nodes List
///
/// This is a list of all peer nodes the internet
/// connections module tries to connect to.
///
/// This message is returned after a request, or when
/// adding or removing a node address.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeshNodesList {
    /// Information about why this message is sent
    /// and the result of the request, adding or removing
    /// of nodes.
    #[prost(enumeration = "Info", tag = "1")]
    pub info: i32,
    /// list of all node multiaddresses that
    /// the internet module will try to connect to.
    #[prost(message, repeated, tag = "2")]
    pub nodes: ::prost::alloc::vec::Vec<MeshNodesEntry>,
}
/// Mesh Nodes Entry
///
/// Contains a node address as a libp2p multiaddress.
/// e.g. "/ip4/144.91.74.192/udp/9229/quic-v1"
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MeshNodesEntry {
    /// address
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// enabled
    #[prost(bool, tag = "2")]
    pub enabled: bool,
    /// name
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
/// Information about the system actions that led to
/// the creation of this message.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Info {
    /// Mesh Nodes Request
    /// By default, this message is sent due to an
    /// mesh nodes request message.
    Request = 0,
    /// Add Internet Node
    /// Successfully added an address
    AddSuccess = 1,
    /// Error: not a valid multiaddress
    AddErrorInvalid = 2,
    /// Remove Internet Node
    /// Successfully removed the address
    RemoveSuccess = 5,
    /// Successfully changed state of the address
    StateSuccess = 6,
    /// Error: Address not found
    RemoveErrorNotFound = 7,
}
impl Info {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Request => "REQUEST",
            Self::AddSuccess => "ADD_SUCCESS",
            Self::AddErrorInvalid => "ADD_ERROR_INVALID",
            Self::RemoveSuccess => "REMOVE_SUCCESS",
            Self::StateSuccess => "STATE_SUCCESS",
            Self::RemoveErrorNotFound => "REMOVE_ERROR_NOT_FOUND",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REQUEST" => Some(Self::Request),
            "ADD_SUCCESS" => Some(Self::AddSuccess),
            "ADD_ERROR_INVALID" => Some(Self::AddErrorInvalid),
            "REMOVE_SUCCESS" => Some(Self::RemoveSuccess),
            "STATE_SUCCESS" => Some(Self::StateSuccess),
            "REMOVE_ERROR_NOT_FOUND" => Some(Self::RemoveErrorNotFound),
            _ => None,
        }
    }
}
